%% =========================================================================
%  HELPER: compute per-parameter normalisation constants
%  Given a specific (H, N_cur, r_k_cur, P_cur, Gam_cur, gam_cur)
%  run omega=1 and omega=0 to get the four EE bounds.
% --------------------------------------------------------------------------
function [EEcmax, EEcmin, EEsmax, EEsmin] = get_norm_constants( ...
        H_cur, theta_targets, N_cur, K, M, ...
        P_cur, sigma2, Gam_cur, gam_cur, ...
        i_b, i_k, P_static,  delta_outage, xi_k_vec , T_max, epsilon, N_rand)

    [~,~, EEcmax_raw, EEsmin_raw, ~] = ...
        solve_ISAC(H_cur, theta_targets, N_cur, K, M, P_cur, sigma2, ...
                   Gam_cur, gam_cur, i_b, i_k, P_static, delta_outage, xi_k_vec, ...
                   1.0, T_max, epsilon, 1, 1, N_rand);

    [~,~, EEcmin_raw, EEsmax_raw, ~] = ...
        solve_ISAC(H_cur, theta_targets, N_cur, K, M, P_cur, sigma2, ...
                   Gam_cur, gam_cur, i_b, i_k, P_static,  delta_outage, xi_k_vec, ...
                   0.0, T_max, epsilon, 1, 1, N_rand);

    EEcmax = max(EEcmax_raw, 1e-9);
    EEsmax = max(EEsmax_raw, 1e-9);
    EEcmin = min(EEcmin_raw, EEcmax - 1e-9);
    EEsmin = min(EEsmin_raw, EEsmax - 1e-9);
end
